"""Asociar permisos a empleados en lugar de departamentos

Revision ID: 06f262905399
Revises: 3e8a3ace7f26
Create Date: 2025-07-08 16:09:40.838897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f262905399'
down_revision = '3e8a3ace7f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permisos', sa.Column('employee_passport', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_permisos_department_id'), table_name='permisos')
    op.create_index(op.f('ix_permisos_employee_passport'), 'permisos', ['employee_passport'], unique=False)
    op.drop_constraint(op.f('permisos_department_id_fkey'), 'permisos', type_='foreignkey')
    op.drop_column('permisos', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permisos', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('permisos_department_id_fkey'), 'permisos', 'personnel_department', ['department_id'], ['id'])
    op.drop_index(op.f('ix_permisos_employee_passport'), table_name='permisos')
    op.create_index(op.f('ix_permisos_department_id'), 'permisos', ['department_id'], unique=False)
    op.drop_column('permisos', 'employee_passport')
    # ### end Alembic commands ###
