"""nueva-tabla

Revision ID: 3e8a3ace7f26
Revises: 642f18f2936f
Create Date: 2025-07-08 16:04:11.483280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8a3ace7f26'
down_revision = '642f18f2936f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_desde', sa.Time(), nullable=False),
    sa.Column('hora_hasta', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['personnel_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_department_id'), 'permisos', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permisos_department_id'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
