"""Creación inicial de tablas

Revision ID: 3eec39e0849d
Revises: 
Create Date: 2025-07-04 09:35:24.326110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eec39e0849d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('carteras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('anulada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('department_horarios_especiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada_especial', sa.Time(), nullable=True),
    sa.Column('hora_salida_especial', sa.Time(), nullable=True),
    sa.Column('horas_extras', sa.Integer(), nullable=True),
    sa.Column('feriado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_horarios_especiales_dept_name'), 'department_horarios_especiales', ['dept_name'], unique=False)
    op.create_index(op.f('ix_department_horarios_especiales_fecha'), 'department_horarios_especiales', ['fecha'], unique=False)
    op.create_table('justificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_passport', sa.String(length=50), nullable=False),
    sa.Column('justification_type', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_justificaciones_employee_passport'), 'justificaciones', ['employee_passport'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('cartera_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cartera_id'], ['carteras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_grupos_cartera_id'), 'grupos', ['cartera_id'], unique=False)
    op.create_table('grupo_empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('employee_passport', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_empleados_employee_passport'), 'grupo_empleados', ['employee_passport'], unique=False)
    op.create_index(op.f('ix_grupo_empleados_grupo_id'), 'grupo_empleados', ['grupo_id'], unique=False)
    op.create_table('grupo_horarios_especiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada_especial', sa.Time(), nullable=True),
    sa.Column('hora_salida_especial', sa.Time(), nullable=True),
    sa.Column('horas_extras', sa.Integer(), nullable=True),
    sa.Column('feriado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_horarios_especiales_fecha'), 'grupo_horarios_especiales', ['fecha'], unique=False)
    op.create_index(op.f('ix_grupo_horarios_especiales_grupo_id'), 'grupo_horarios_especiales', ['grupo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grupo_horarios_especiales_grupo_id'), table_name='grupo_horarios_especiales')
    op.drop_index(op.f('ix_grupo_horarios_especiales_fecha'), table_name='grupo_horarios_especiales')
    op.drop_table('grupo_horarios_especiales')
    op.drop_index(op.f('ix_grupo_empleados_grupo_id'), table_name='grupo_empleados')
    op.drop_index(op.f('ix_grupo_empleados_employee_passport'), table_name='grupo_empleados')
    op.drop_table('grupo_empleados')
    op.drop_index(op.f('ix_grupos_cartera_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_justificaciones_employee_passport'), table_name='justificaciones')
    op.drop_table('justificaciones')
    op.drop_index(op.f('ix_department_horarios_especiales_fecha'), table_name='department_horarios_especiales')
    op.drop_index(op.f('ix_department_horarios_especiales_dept_name'), table_name='department_horarios_especiales')
    op.drop_table('department_horarios_especiales')
    op.drop_table('carteras')
    op.drop_table('allowed_ips')
    # ### end Alembic commands ###
