"""Añadir campo anulada a justificaciones

Revision ID: 457ed4673ec3
Revises: 3eec39e0849d
Create Date: ...

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457ed4673ec3'
down_revision = '3eec39e0849d' # Revisa que este ID sea el de tu migración anterior
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('justificaciones', sa.Column('anulada', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('justificaciones', 'anulada')
    # ### end Alembic commands ###