"""nueva-tabla

Revision ID: 642f18f2936f
Revises: 457ed4673ec3
Create Date: 2025-07-08 16:00:21.267836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642f18f2936f'
down_revision = '457ed4673ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
